default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50
  timeout: 5000
  template: template0

development:
  <<: *default
  database: e-commerce-api
  host: localhost
  username: postgres
  password: postgres